/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kvsys_CONSTANTS_H
#define kvsys_CONSTANTS_H

#include "kvsys_types.h"



class kvsysConstants {
 public:
  kvsysConstants();

};

extern const kvsysConstants g_kvsys_constants;



#endif
