/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kvsys_constants.h"



const kvsysConstants g_kvsys_constants;

kvsysConstants::kvsysConstants() {
}



