// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "tagService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class tagServiceHandler : virtual public tagServiceIf {
 public:
  tagServiceHandler() {
    // Your initialization goes here
  }

  void getTag(std::string& _return, const int16_t tid) {
    // Your implementation goes here
    printf("getTag\n");
  }

  int16_t getTid(const std::string& tag) {
    // Your implementation goes here
    printf("getTid\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<tagServiceHandler> handler(new tagServiceHandler());
  shared_ptr<TProcessor> processor(new tagServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

